name: myapp
functions:
  - name: allfunctions
    github:
      repo: Misfits09/sls-do
      branch: master
      deploy_on_push: true
    source_dir: ./backend
    envs:
      - key: FRONT_URL
        value: "${allstatics.PUBLIC_URL}"
        scope: RUN_TIME
    routes:
      - path: /api
static_sites:
  - name: allstatics
    github:
      repo: Misfits09/sls-do
      branch: master
      deploy_on_push: true
    source_dir: ./frontend
    build_command: npm run export
    output_dir: _static
    envs:
      - key: BACK_URL
        value: "${allfunctions.PUBLIC_URL}"
        scope: BUILD_TIME