name: myapp
functions:
  - name: allfunctions
    github:
      repo: Misfits09/sls-do
      branch: master
      deploy_on_push: true
    source_dir: ./backend
    routes:
      - path: /api
static_sites:
  - name: allstatics
    github:
      repo: Misfits09/sls-do
      branch: master
      deploy_on_push: true
    source_dir: ./frontend